### PR TITLE
Testing Math-magicians website

### PR DESCRIPTION
**Pull request by t-yanick**
In this PR we:
- Setup tests for our react math magicians website.
- Add unit tests for the calculate.js file
- Use jest snapshots to ensure that all elements are displayed at the Home, Calculator, and Quote pages

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes Required :muscle: 
Hello @t-yanick :hand: 
Good job testing your application so far.
But we need to make more tests before moving on.

- [x] Nice job creating snapshots and testing with the components are rendering. But we also need to implement tests for the logic part of the calculator app. We need to implement tests for both calculate and operate functions. For the `calculate`, we need to implement tests for every possible case and assure that the application is behaving as it is expected. For the `operate` function, we need to implement tests for all operations and assure that the outcome is going to be the expected result.
Screenshot from 2021-05-18 21-15-58

- [ ] There is a console error being logged in one of the tests. Is related to a missing prop in one component. Let's fix it
Screenshot from 2021-05-18 21-08-53

Happy coding :computer: 
**Sérgio Torres**

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @t-yanick, great job so far with the test :fireworks: The console errors now resolved and most of the functionality is tested. :muscle: However, how to test the converting of a number into a percentage is not tested. Kindly check the `operate.test.js` file and check the missing operation :smile: 

Once this is resolved, kindly submit another code review request :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by t-yanick** [comment]
Hi @addod19, Thanks for your feedback. The test for `%` is found in `calculate.test.js` because `%` accepts 2 arguments while the 4 operations in have in `operate.test.js` accepts 3 arguments. Thanks

**Review by Torres-ssf — APPROVED** [review]
### PR Approved :+1: 
Hello again @t-yanick :hand: 
Good job adding more tests to your application :clap: 
Good luck with the next project

Happy coding :computer: 
**Sérgio Torres**

**Pull request merged**
